In [1]:
# Import dependencies
import pandas as pd
from pathlib import Path
import numpy as np

In [2]:
# Upload file, convert to dataframe
attendance = pd.read_csv('../CSP_Data/activities_attendance.csv')
attendance

,Attendance ID,Activity Name,Activity Instance ID,Activity Label,Person ID,Date,Attended (y/n),Minutes Attended,Lead Staff Name,Individual Activity - Notes,Individual Activity - Referral Service,Individual Activity - Referral Agency,Individual Activity - Referral Date
0,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46887178,9/10/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
1,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46887178,9/17/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
2,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46887178,9/24/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
3,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46887178,10/1/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
4,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46887178,10/15/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
5,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46887178,10/22/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
6,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46887178,10/29/2018,Y,240.0,NaN,NaN,NaN,NaN,NaN
7,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46891897,9/10/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
8,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46891897,9/17/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
9,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46891897,9/24/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
10,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46891897,10/1/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
11,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46891897,10/15/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
12,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46891897,10/22/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
13,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46891897,10/29/2018,Y,240.0,NaN,NaN,NaN,NaN,NaN
14,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46891989,9/10/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
15,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46891989,9/17/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
16,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46891989,9/24/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
17,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46891989,10/1/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
18,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46891989,10/15/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
19,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46891989,10/22/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
20,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46891989,10/29/2018,Y,240.0,NaN,NaN,NaN,NaN,NaN
21,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46894320,9/10/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
22,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46894320,9/17/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
23,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46894320,9/24/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
24,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46894320,10/1/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
25,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46894320,10/15/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
26,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46894320,10/22/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
27,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46894320,10/29/2018,Y,240.0,NaN,NaN,NaN,NaN,NaN
28,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46897487,9/10/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
29,NaN,Surfing 101 Middle School,3383538,Aptos Surfing 101 Course,46897487,9/17/2018,Y,360.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5531,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46893469,6/25/2019,N,0.0,NaN,NaN,NaN,NaN,NaN
5532,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46893469,6/26/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5533,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46893469,6/27/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5534,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46893706,6/25/2019,N,0.0,NaN,NaN,NaN,NaN,NaN
5535,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46893706,6/26/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5536,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46893706,6/27/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5537,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46894801,6/25/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5538,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46894801,6/26/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5539,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46894801,6/27/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5540,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46894961,6/25/2019,N,0.0,NaN,NaN,NaN,NaN,NaN
5541,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46894961,6/26/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5542,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46894961,6/27/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5543,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46896188,6/25/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5544,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46896188,6/26/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5545,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46896188,6/27/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5546,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46900770,6/25/2019,N,0.0,NaN,NaN,NaN,NaN,NaN
5547,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46900770,6/26/2019,N,0.0,NaN,NaN,NaN,NaN,NaN
5548,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46900770,6/27/2019,N,0.0,NaN,NaN,NaN,NaN,NaN
5549,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46901050,6/25/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5550,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46901050,6/26/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5551,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46901050,6/27/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5552,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46908175,6/25/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5553,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46908175,6/26/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5554,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,46908175,6/27/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5555,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,47411223,6/25/2019,N,0.0,NaN,NaN,NaN,NaN,NaN
5556,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,47411223,6/26/2019,N,0.0,NaN,NaN,NaN,NaN,NaN
5557,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,47411223,6/27/2019,N,0.0,NaN,NaN,NaN,NaN,NaN
5558,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,47433659,6/25/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5559,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,47433659,6/26/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN
5560,NaN,Surfers In Leadership Training (SILT),3621424,SILT SUMMER CAMP SESSION 2: Booker T. Washington,47433659,6/27/2019,Y,420.0,NaN,NaN,NaN,NaN,NaN

In [3]:
# Check data types
attendance.dtypes

Attendance ID                             float64
Activity Name                              object
Activity Instance ID                        int64
Activity Label                             object
Person ID                                   int64
Date                                       object
Attended (y/n)                             object
Minutes Attended                          float64
Lead Staff Name                            object
Individual Activity - Notes               float64
Individual Activity - Referral Service    float64
Individual Activity - Referral Agency     float64
Individual Activity - Referral Date       float64
dtype: object

In [5]:
# Drop columns we do not want in schema
attendance = attendance.drop(columns = ["Attendance ID", "Activity Label", "Lead Staff Name", "Individual Activity - Notes", "Individual Activity - Referral Service", "Individual Activity - Referral Agency", "Individual Activity - Referral Date"])
attendance

,Activity Name,Activity Instance ID,Person ID,Date,Attended (y/n),Minutes Attended
0,Surfing 101 Middle School,3383538,46887178,9/10/2018,Y,360.0
1,Surfing 101 Middle School,3383538,46887178,9/17/2018,Y,360.0
2,Surfing 101 Middle School,3383538,46887178,9/24/2018,Y,360.0
3,Surfing 101 Middle School,3383538,46887178,10/1/2018,Y,360.0
4,Surfing 101 Middle School,3383538,46887178,10/15/2018,Y,360.0
5,Surfing 101 Middle School,3383538,46887178,10/22/2018,Y,360.0
6,Surfing 101 Middle School,3383538,46887178,10/29/2018,Y,240.0
7,Surfing 101 Middle School,3383538,46891897,9/10/2018,Y,360.0
8,Surfing 101 Middle School,3383538,46891897,9/17/2018,Y,360.0
9,Surfing 101 Middle School,3383538,46891897,9/24/2018,Y,360.0
10,Surfing 101 Middle School,3383538,46891897,10/1/2018,Y,360.0
11,Surfing 101 Middle School,3383538,46891897,10/15/2018,Y,360.0
12,Surfing 101 Middle School,3383538,46891897,10/22/2018,Y,360.0
13,Surfing 101 Middle School,3383538,46891897,10/29/2018,Y,240.0
14,Surfing 101 Middle School,3383538,46891989,9/10/2018,Y,360.0
15,Surfing 101 Middle School,3383538,46891989,9/17/2018,Y,360.0
16,Surfing 101 Middle School,3383538,46891989,9/24/2018,Y,360.0
17,Surfing 101 Middle School,3383538,46891989,10/1/2018,Y,360.0
18,Surfing 101 Middle School,3383538,46891989,10/15/2018,Y,360.0
19,Surfing 101 Middle School,3383538,46891989,10/22/2018,Y,360.0
20,Surfing 101 Middle School,3383538,46891989,10/29/2018,Y,240.0
21,Surfing 101 Middle School,3383538,46894320,9/10/2018,Y,360.0
22,Surfing 101 Middle School,3383538,46894320,9/17/2018,Y,360.0
23,Surfing 101 Middle School,3383538,46894320,9/24/2018,Y,360.0
24,Surfing 101 Middle School,3383538,46894320,10/1/2018,Y,360.0
25,Surfing 101 Middle School,3383538,46894320,10/15/2018,Y,360.0
26,Surfing 101 Middle School,3383538,46894320,10/22/2018,Y,360.0
27,Surfing 101 Middle School,3383538,46894320,10/29/2018,Y,240.0
28,Surfing 101 Middle School,3383538,46897487,9/10/2018,Y,360.0
29,Surfing 101 Middle School,3383538,46897487,9/17/2018,Y,360.0
...,...,...,...,...,...,...
5531,Surfers In Leadership Training (SILT),3621424,46893469,6/25/2019,N,0.0
5532,Surfers In Leadership Training (SILT),3621424,46893469,6/26/2019,Y,420.0
5533,Surfers In Leadership Training (SILT),3621424,46893469,6/27/2019,Y,420.0
5534,Surfers In Leadership Training (SILT),3621424,46893706,6/25/2019,N,0.0
5535,Surfers In Leadership Training (SILT),3621424,46893706,6/26/2019,Y,420.0
5536,Surfers In Leadership Training (SILT),3621424,46893706,6/27/2019,Y,420.0
5537,Surfers In Leadership Training (SILT),3621424,46894801,6/25/2019,Y,420.0
5538,Surfers In Leadership Training (SILT),3621424,46894801,6/26/2019,Y,420.0
5539,Surfers In Leadership Training (SILT),3621424,46894801,6/27/2019,Y,420.0
5540,Surfers In Leadership Training (SILT),3621424,46894961,6/25/2019,N,0.0
5541,Surfers In Leadership Training (SILT),3621424,46894961,6/26/2019,Y,420.0
5542,Surfers In Leadership Training (SILT),3621424,46894961,6/27/2019,Y,420.0
5543,Surfers In Leadership Training (SILT),3621424,46896188,6/25/2019,Y,420.0
5544,Surfers In Leadership Training (SILT),3621424,46896188,6/26/2019,Y,420.0
5545,Surfers In Leadership Training (SILT),3621424,46896188,6/27/2019,Y,420.0
5546,Surfers In Leadership Training (SILT),3621424,46900770,6/25/2019,N,0.0
5547,Surfers In Leadership Training (SILT),3621424,46900770,6/26/2019,N,0.0
5548,Surfers In Leadership Training (SILT),3621424,46900770,6/27/2019,N,0.0
5549,Surfers In Leadership Training (SILT),3621424,46901050,6/25/2019,Y,420.0
5550,Surfers In Leadership Training (SILT),3621424,46901050,6/26/2019,Y,420.0
5551,Surfers In Leadership Training (SILT),3621424,46901050,6/27/2019,Y,420.0
5552,Surfers In Leadership Training (SILT),3621424,46908175,6/25/2019,Y,420.0
5553,Surfers In Leadership Training (SILT),3621424,46908175,6/26/2019,Y,420.0
5554,Surfers In Leadership Training (SILT),3621424,46908175,6/27/2019,Y,420.0
5555,Surfers In Leadership Training (SILT),3621424,47411223,6/25/2019,N,0.0
5556,Surfers In Leadership Training (SILT),3621424,47411223,6/26/2019,N,0.0
5557,Surfers In Leadership Training (SILT),3621424,47411223,6/27/2019,N,0.0
5558,Surfers In Leadership Training (SILT),3621424,47433659,6/25/2019,Y,420.0
5559,Surfers In Leadership Training (SILT),3621424,47433659,6/26/2019,Y,420.0
5560,Surfers In Leadership Training (SILT),3621424,47433659,6/27/2019,Y,420.0

In [6]:
# Rename columns
attendance_df = attendance.rename(columns={
                          'Person ID':'Participant ID',
                            'Attended (y/n)':'Attended'
})
attendance_df

,Activity Name,Activity Instance ID,Participant ID,Date,Attended,Minutes Attended
0,Surfing 101 Middle School,3383538,46887178,9/10/2018,Y,360.0
1,Surfing 101 Middle School,3383538,46887178,9/17/2018,Y,360.0
2,Surfing 101 Middle School,3383538,46887178,9/24/2018,Y,360.0
3,Surfing 101 Middle School,3383538,46887178,10/1/2018,Y,360.0
4,Surfing 101 Middle School,3383538,46887178,10/15/2018,Y,360.0
5,Surfing 101 Middle School,3383538,46887178,10/22/2018,Y,360.0
6,Surfing 101 Middle School,3383538,46887178,10/29/2018,Y,240.0
7,Surfing 101 Middle School,3383538,46891897,9/10/2018,Y,360.0
8,Surfing 101 Middle School,3383538,46891897,9/17/2018,Y,360.0
9,Surfing 101 Middle School,3383538,46891897,9/24/2018,Y,360.0
10,Surfing 101 Middle School,3383538,46891897,10/1/2018,Y,360.0
11,Surfing 101 Middle School,3383538,46891897,10/15/2018,Y,360.0
12,Surfing 101 Middle School,3383538,46891897,10/22/2018,Y,360.0
13,Surfing 101 Middle School,3383538,46891897,10/29/2018,Y,240.0
14,Surfing 101 Middle School,3383538,46891989,9/10/2018,Y,360.0
15,Surfing 101 Middle School,3383538,46891989,9/17/2018,Y,360.0
16,Surfing 101 Middle School,3383538,46891989,9/24/2018,Y,360.0
17,Surfing 101 Middle School,3383538,46891989,10/1/2018,Y,360.0
18,Surfing 101 Middle School,3383538,46891989,10/15/2018,Y,360.0
19,Surfing 101 Middle School,3383538,46891989,10/22/2018,Y,360.0
20,Surfing 101 Middle School,3383538,46891989,10/29/2018,Y,240.0
21,Surfing 101 Middle School,3383538,46894320,9/10/2018,Y,360.0
22,Surfing 101 Middle School,3383538,46894320,9/17/2018,Y,360.0
23,Surfing 101 Middle School,3383538,46894320,9/24/2018,Y,360.0
24,Surfing 101 Middle School,3383538,46894320,10/1/2018,Y,360.0
25,Surfing 101 Middle School,3383538,46894320,10/15/2018,Y,360.0
26,Surfing 101 Middle School,3383538,46894320,10/22/2018,Y,360.0
27,Surfing 101 Middle School,3383538,46894320,10/29/2018,Y,240.0
28,Surfing 101 Middle School,3383538,46897487,9/10/2018,Y,360.0
29,Surfing 101 Middle School,3383538,46897487,9/17/2018,Y,360.0
...,...,...,...,...,...,...
5531,Surfers In Leadership Training (SILT),3621424,46893469,6/25/2019,N,0.0
5532,Surfers In Leadership Training (SILT),3621424,46893469,6/26/2019,Y,420.0
5533,Surfers In Leadership Training (SILT),3621424,46893469,6/27/2019,Y,420.0
5534,Surfers In Leadership Training (SILT),3621424,46893706,6/25/2019,N,0.0
5535,Surfers In Leadership Training (SILT),3621424,46893706,6/26/2019,Y,420.0
5536,Surfers In Leadership Training (SILT),3621424,46893706,6/27/2019,Y,420.0
5537,Surfers In Leadership Training (SILT),3621424,46894801,6/25/2019,Y,420.0
5538,Surfers In Leadership Training (SILT),3621424,46894801,6/26/2019,Y,420.0
5539,Surfers In Leadership Training (SILT),3621424,46894801,6/27/2019,Y,420.0
5540,Surfers In Leadership Training (SILT),3621424,46894961,6/25/2019,N,0.0
5541,Surfers In Leadership Training (SILT),3621424,46894961,6/26/2019,Y,420.0
5542,Surfers In Leadership Training (SILT),3621424,46894961,6/27/2019,Y,420.0
5543,Surfers In Leadership Training (SILT),3621424,46896188,6/25/2019,Y,420.0
5544,Surfers In Leadership Training (SILT),3621424,46896188,6/26/2019,Y,420.0
5545,Surfers In Leadership Training (SILT),3621424,46896188,6/27/2019,Y,420.0
5546,Surfers In Leadership Training (SILT),3621424,46900770,6/25/2019,N,0.0
5547,Surfers In Leadership Training (SILT),3621424,46900770,6/26/2019,N,0.0
5548,Surfers In Leadership Training (SILT),3621424,46900770,6/27/2019,N,0.0
5549,Surfers In Leadership Training (SILT),3621424,46901050,6/25/2019,Y,420.0
5550,Surfers In Leadership Training (SILT),3621424,46901050,6/26/2019,Y,420.0
5551,Surfers In Leadership Training (SILT),3621424,46901050,6/27/2019,Y,420.0
5552,Surfers In Leadership Training (SILT),3621424,46908175,6/25/2019,Y,420.0
5553,Surfers In Leadership Training (SILT),3621424,46908175,6/26/2019,Y,420.0
5554,Surfers In Leadership Training (SILT),3621424,46908175,6/27/2019,Y,420.0
5555,Surfers In Leadership Training (SILT),3621424,47411223,6/25/2019,N,0.0
5556,Surfers In Leadership Training (SILT),3621424,47411223,6/26/2019,N,0.0
5557,Surfers In Leadership Training (SILT),3621424,47411223,6/27/2019,N,0.0
5558,Surfers In Leadership Training (SILT),3621424,47433659,6/25/2019,Y,420.0
5559,Surfers In Leadership Training (SILT),3621424,47433659,6/26/2019,Y,420.0
5560,Surfers In Leadership Training (SILT),3621424,47433659,6/27/2019,Y,420.0

In [7]:
# Value counts for each program
attendance_df["Activity Name"].value_counts()

Surfing 101                              4981
Surfing 101 Middle School                 338
Surfers In Leadership Training (SILT)     242
Name: Activity Name, dtype: int64

# Create df by Program - SILT / Surfing 101 MS / Surfing 101 HS

In [8]:
# Filter by Program -SILT
is_silt = attendance_df['Activity Name'] == 'Surfers In Leadership Training (SILT)'
is_silt.head()

0    False
1    False
2    False
3    False
4    False
Name: Activity Name, dtype: bool

In [9]:
# Df for silt
silt_df = attendance_df[is_silt]
silt_df

,Activity Name,Activity Instance ID,Participant ID,Date,Attended,Minutes Attended
4266,Surfers In Leadership Training (SILT),3421146,46843398,8/1/2018,N,0.0
4267,Surfers In Leadership Training (SILT),3421146,46843398,8/2/2018,N,0.0
4268,Surfers In Leadership Training (SILT),3421146,46853927,8/1/2018,N,0.0
4269,Surfers In Leadership Training (SILT),3421146,46853927,8/2/2018,N,0.0
4270,Surfers In Leadership Training (SILT),3421146,46854059,8/1/2018,Y,480.0
4271,Surfers In Leadership Training (SILT),3421146,46854059,8/2/2018,Y,480.0
4272,Surfers In Leadership Training (SILT),3421146,46856130,8/1/2018,N,0.0
4273,Surfers In Leadership Training (SILT),3421146,46856130,8/2/2018,N,0.0
4274,Surfers In Leadership Training (SILT),3421146,46857834,8/1/2018,Y,480.0
4275,Surfers In Leadership Training (SILT),3421146,46857834,8/2/2018,Y,480.0
4276,Surfers In Leadership Training (SILT),3421146,46861804,8/1/2018,Y,480.0
4277,Surfers In Leadership Training (SILT),3421146,46861804,8/2/2018,Y,480.0
4278,Surfers In Leadership Training (SILT),3421146,46864094,8/1/2018,N,0.0
4279,Surfers In Leadership Training (SILT),3421146,46864094,8/2/2018,N,0.0
4280,Surfers In Leadership Training (SILT),3421146,46864770,8/1/2018,N,0.0
4281,Surfers In Leadership Training (SILT),3421146,46864770,8/2/2018,N,0.0
4282,Surfers In Leadership Training (SILT),3421146,46865225,8/1/2018,N,0.0
4283,Surfers In Leadership Training (SILT),3421146,46865225,8/2/2018,N,0.0
4284,Surfers In Leadership Training (SILT),3421146,46866228,8/1/2018,N,0.0
4285,Surfers In Leadership Training (SILT),3421146,46866228,8/2/2018,N,0.0
4286,Surfers In Leadership Training (SILT),3421146,46867140,8/1/2018,N,0.0
4287,Surfers In Leadership Training (SILT),3421146,46867140,8/2/2018,N,0.0
4288,Surfers In Leadership Training (SILT),3421146,46869126,8/1/2018,N,0.0
4289,Surfers In Leadership Training (SILT),3421146,46869126,8/2/2018,N,0.0
4290,Surfers In Leadership Training (SILT),3421146,46871778,8/1/2018,N,0.0
4291,Surfers In Leadership Training (SILT),3421146,46871778,8/2/2018,N,0.0
4292,Surfers In Leadership Training (SILT),3421146,46872664,8/1/2018,N,0.0
4293,Surfers In Leadership Training (SILT),3421146,46872664,8/2/2018,N,0.0
4294,Surfers In Leadership Training (SILT),3421146,46872848,8/1/2018,Y,480.0
4295,Surfers In Leadership Training (SILT),3421146,46872848,8/2/2018,Y,480.0
...,...,...,...,...,...,...
5531,Surfers In Leadership Training (SILT),3621424,46893469,6/25/2019,N,0.0
5532,Surfers In Leadership Training (SILT),3621424,46893469,6/26/2019,Y,420.0
5533,Surfers In Leadership Training (SILT),3621424,46893469,6/27/2019,Y,420.0
5534,Surfers In Leadership Training (SILT),3621424,46893706,6/25/2019,N,0.0
5535,Surfers In Leadership Training (SILT),3621424,46893706,6/26/2019,Y,420.0
5536,Surfers In Leadership Training (SILT),3621424,46893706,6/27/2019,Y,420.0
5537,Surfers In Leadership Training (SILT),3621424,46894801,6/25/2019,Y,420.0
5538,Surfers In Leadership Training (SILT),3621424,46894801,6/26/2019,Y,420.0
5539,Surfers In Leadership Training (SILT),3621424,46894801,6/27/2019,Y,420.0
5540,Surfers In Leadership Training (SILT),3621424,46894961,6/25/2019,N,0.0
5541,Surfers In Leadership Training (SILT),3621424,46894961,6/26/2019,Y,420.0
5542,Surfers In Leadership Training (SILT),3621424,46894961,6/27/2019,Y,420.0
5543,Surfers In Leadership Training (SILT),3621424,46896188,6/25/2019,Y,420.0
5544,Surfers In Leadership Training (SILT),3621424,46896188,6/26/2019,Y,420.0
5545,Surfers In Leadership Training (SILT),3621424,46896188,6/27/2019,Y,420.0
5546,Surfers In Leadership Training (SILT),3621424,46900770,6/25/2019,N,0.0
5547,Surfers In Leadership Training (SILT),3621424,46900770,6/26/2019,N,0.0
5548,Surfers In Leadership Training (SILT),3621424,46900770,6/27/2019,N,0.0
5549,Surfers In Leadership Training (SILT),3621424,46901050,6/25/2019,Y,420.0
5550,Surfers In Leadership Training (SILT),3621424,46901050,6/26/2019,Y,420.0
5551,Surfers In Leadership Training (SILT),3621424,46901050,6/27/2019,Y,420.0
5552,Surfers In Leadership Training (SILT),3621424,46908175,6/25/2019,Y,420.0
5553,Surfers In Leadership Training (SILT),3621424,46908175,6/26/2019,Y,420.0
5554,Surfers In Leadership Training (SILT),3621424,46908175,6/27/2019,Y,420.0
5555,Surfers In Leadership Training (SILT),3621424,47411223,6/25/2019,N,0.0
5556,Surfers In Leadership Training (SILT),3621424,47411223,6/26/2019,N,0.0
5557,Surfers In Leadership Training (SILT),3621424,47411223,6/27/2019,N,0.0
5558,Surfers In Leadership Training (SILT),3621424,47433659,6/25/2019,Y,420.0
5559,Surfers In Leadership Training (SILT),3621424,47433659,6/26/2019,Y,420.0
5560,Surfers In Leadership Training (SILT),3621424,47433659,6/27/2019,Y,420.0

In [10]:
## Filter by Program - Middle School 101
is_surfing_101_MS = attendance_df['Activity Name'] == 'Surfing 101 Middle School '
is_surfing_101_MS

0        True
1        True
2        True
3        True
4        True
5        True
6        True
7        True
8        True
9        True
10       True
11       True
12       True
13       True
14       True
15       True
16       True
17       True
18       True
19       True
20       True
21       True
22       True
23       True
24       True
25       True
26       True
27       True
28       True
29       True
        ...
5531    False
5532    False
5533    False
5534    False
5535    False
5536    False
5537    False
5538    False
5539    False
5540    False
5541    False
5542    False
5543    False
5544    False
5545    False
5546    False
5547    False
5548    False
5549    False
5550    False
5551    False
5552    False
5553    False
5554    False
5555    False
5556    False
5557    False
5558    False
5559    False
5560    False
Name: Activity Name, Length: 5561, dtype: bool

In [11]:
# Df for MS Surfing 101
surf_101_MS_df = attendance_df[is_surfing_101_MS]
surf_101_MS_df

,Activity Name,Activity Instance ID,Participant ID,Date,Attended,Minutes Attended
0,Surfing 101 Middle School,3383538,46887178,9/10/2018,Y,360.0
1,Surfing 101 Middle School,3383538,46887178,9/17/2018,Y,360.0
2,Surfing 101 Middle School,3383538,46887178,9/24/2018,Y,360.0
3,Surfing 101 Middle School,3383538,46887178,10/1/2018,Y,360.0
4,Surfing 101 Middle School,3383538,46887178,10/15/2018,Y,360.0
5,Surfing 101 Middle School,3383538,46887178,10/22/2018,Y,360.0
6,Surfing 101 Middle School,3383538,46887178,10/29/2018,Y,240.0
7,Surfing 101 Middle School,3383538,46891897,9/10/2018,Y,360.0
8,Surfing 101 Middle School,3383538,46891897,9/17/2018,Y,360.0
9,Surfing 101 Middle School,3383538,46891897,9/24/2018,Y,360.0
10,Surfing 101 Middle School,3383538,46891897,10/1/2018,Y,360.0
11,Surfing 101 Middle School,3383538,46891897,10/15/2018,Y,360.0
12,Surfing 101 Middle School,3383538,46891897,10/22/2018,Y,360.0
13,Surfing 101 Middle School,3383538,46891897,10/29/2018,Y,240.0
14,Surfing 101 Middle School,3383538,46891989,9/10/2018,Y,360.0
15,Surfing 101 Middle School,3383538,46891989,9/17/2018,Y,360.0
16,Surfing 101 Middle School,3383538,46891989,9/24/2018,Y,360.0
17,Surfing 101 Middle School,3383538,46891989,10/1/2018,Y,360.0
18,Surfing 101 Middle School,3383538,46891989,10/15/2018,Y,360.0
19,Surfing 101 Middle School,3383538,46891989,10/22/2018,Y,360.0
20,Surfing 101 Middle School,3383538,46891989,10/29/2018,Y,240.0
21,Surfing 101 Middle School,3383538,46894320,9/10/2018,Y,360.0
22,Surfing 101 Middle School,3383538,46894320,9/17/2018,Y,360.0
23,Surfing 101 Middle School,3383538,46894320,9/24/2018,Y,360.0
24,Surfing 101 Middle School,3383538,46894320,10/1/2018,Y,360.0
25,Surfing 101 Middle School,3383538,46894320,10/15/2018,Y,360.0
26,Surfing 101 Middle School,3383538,46894320,10/22/2018,Y,360.0
27,Surfing 101 Middle School,3383538,46894320,10/29/2018,Y,240.0
28,Surfing 101 Middle School,3383538,46897487,9/10/2018,Y,360.0
29,Surfing 101 Middle School,3383538,46897487,9/17/2018,Y,360.0
...,...,...,...,...,...,...
5124,Surfing 101 Middle School,3508595,46904597,5/13/2019,Y,225.0
5125,Surfing 101 Middle School,3508595,46904597,5/20/2019,Y,225.0
5126,Surfing 101 Middle School,3508595,46904597,6/3/2019,Y,225.0
5127,Surfing 101 Middle School,3508595,46906175,4/1/2019,Y,225.0
5128,Surfing 101 Middle School,3508595,46906175,4/8/2019,Y,225.0
5129,Surfing 101 Middle School,3508595,46906175,4/15/2019,Y,225.0
5130,Surfing 101 Middle School,3508595,46906175,4/22/2019,Y,225.0
5131,Surfing 101 Middle School,3508595,46906175,4/29/2019,Y,225.0
5132,Surfing 101 Middle School,3508595,46906175,5/6/2019,Y,225.0
5133,Surfing 101 Middle School,3508595,46906175,5/13/2019,Y,225.0
5134,Surfing 101 Middle School,3508595,46906175,5/20/2019,Y,225.0
5135,Surfing 101 Middle School,3508595,46906175,6/3/2019,N,0.0
5136,Surfing 101 Middle School,3508595,46907807,4/1/2019,Y,225.0
5137,Surfing 101 Middle School,3508595,46907807,4/8/2019,Y,225.0
5138,Surfing 101 Middle School,3508595,46907807,4/15/2019,Y,225.0
5139,Surfing 101 Middle School,3508595,46907807,4/22/2019,Y,225.0
5140,Surfing 101 Middle School,3508595,46907807,4/29/2019,Y,225.0
5141,Surfing 101 Middle School,3508595,46907807,5/6/2019,Y,225.0
5142,Surfing 101 Middle School,3508595,46907807,5/13/2019,Y,225.0
5143,Surfing 101 Middle School,3508595,46907807,5/20/2019,Y,225.0
5144,Surfing 101 Middle School,3508595,46907807,6/3/2019,Y,225.0
5145,Surfing 101 Middle School,3508595,46908729,4/1/2019,N,0.0
5146,Surfing 101 Middle School,3508595,46908729,4/8/2019,N,0.0
5147,Surfing 101 Middle School,3508595,46908729,4/15/2019,N,0.0
5148,Surfing 101 Middle School,3508595,46908729,4/22/2019,N,0.0
5149,Surfing 101 Middle School,3508595,46908729,4/29/2019,N,0.0
5150,Surfing 101 Middle School,3508595,46908729,5/6/2019,Y,225.0
5151,Surfing 101 Middle School,3508595,46908729,5/13/2019,Y,225.0
5152,Surfing 101 Middle School,3508595,46908729,5/20/2019,Y,225.0
5153,Surfing 101 Middle School,3508595,46908729,6/3/2019,N,0.0

In [12]:
# Filter by HS Surfing 101
surf_101_HS = attendance_df['Activity Name'] == 'Surfing 101'
surf_101_HS

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
5531    False
5532    False
5533    False
5534    False
5535    False
5536    False
5537    False
5538    False
5539    False
5540    False
5541    False
5542    False
5543    False
5544    False
5545    False
5546    False
5547    False
5548    False
5549    False
5550    False
5551    False
5552    False
5553    False
5554    False
5555    False
5556    False
5557    False
5558    False
5559    False
5560    False
Name: Activity Name, Length: 5561, dtype: bool

In [13]:
# Df for HS surfing 101
surf_101_HS_df = attendance_df[surf_101_HS]
surf_101_HS_df

,Activity Name,Activity Instance ID,Participant ID,Date,Attended,Minutes Attended
70,Surfing 101,3384580,46843252,8/20/2018,Y,180.0
71,Surfing 101,3384580,46843252,8/22/2018,Y,180.0
72,Surfing 101,3384580,46843252,8/24/2018,Y,300.0
73,Surfing 101,3384580,46843252,8/27/2018,Y,180.0
74,Surfing 101,3384580,46843252,8/29/2018,Y,180.0
75,Surfing 101,3384580,46843252,8/31/2018,Y,300.0
76,Surfing 101,3384580,46843252,9/3/2018,Y,180.0
77,Surfing 101,3384580,46843252,9/5/2018,Y,180.0
78,Surfing 101,3384580,46843252,9/7/2018,Y,300.0
79,Surfing 101,3384580,46843252,9/10/2018,Y,180.0
80,Surfing 101,3384580,46843252,9/12/2018,Y,180.0
81,Surfing 101,3384580,46843252,9/14/2018,N,0.0
82,Surfing 101,3384580,46843252,9/17/2018,Y,180.0
83,Surfing 101,3384580,46843252,9/19/2018,Y,180.0
84,Surfing 101,3384580,46843252,9/21/2018,N,0.0
85,Surfing 101,3384580,46843252,9/24/2018,Y,180.0
86,Surfing 101,3384580,46843252,9/26/2018,Y,180.0
87,Surfing 101,3384580,46843252,9/28/2018,Y,300.0
88,Surfing 101,3384580,46843252,10/1/2018,Y,180.0
89,Surfing 101,3384580,46843252,10/3/2018,Y,180.0
90,Surfing 101,3384580,46843252,10/5/2018,N,0.0
91,Surfing 101,3384580,46843252,10/8/2018,Y,180.0
92,Surfing 101,3384580,46843252,10/10/2018,Y,180.0
93,Surfing 101,3384580,46843252,10/12/2018,N,0.0
94,Surfing 101,3384580,46843252,10/15/2018,Y,180.0
95,Surfing 101,3384580,46843252,10/17/2018,Y,180.0
96,Surfing 101,3384580,46843252,10/19/2018,Y,300.0
97,Surfing 101,3384580,46843252,10/22/2018,Y,180.0
98,Surfing 101,3384580,46843252,10/24/2018,Y,180.0
99,Surfing 101,3384580,46843252,10/26/2018,Y,300.0
...,...,...,...,...,...,...
5371,Surfing 101,3620598,46879323,5/11/2019,Y,360.0
5372,Surfing 101,3620598,46884509,5/11/2019,Y,360.0
5373,Surfing 101,3620598,46904225,5/11/2019,Y,360.0
5374,Surfing 101,3620600,46867820,5/18/2019,Y,360.0
5375,Surfing 101,3620600,46869166,5/18/2019,Y,360.0
5376,Surfing 101,3620600,46878634,5/18/2019,Y,360.0
5377,Surfing 101,3620600,46879489,5/18/2019,Y,360.0
5378,Surfing 101,3620600,46886856,5/18/2019,Y,360.0
5379,Surfing 101,3620656,46847012,5/18/2019,Y,360.0
5380,Surfing 101,3620656,46857834,5/18/2019,Y,360.0
5381,Surfing 101,3620656,46861804,5/18/2019,Y,360.0
5382,Surfing 101,3620656,46875282,5/18/2019,Y,360.0
5383,Surfing 101,3620656,47343704,5/18/2019,Y,360.0
5384,Surfing 101,3620656,47346915,5/18/2019,Y,360.0
5385,Surfing 101,3620940,46843808,4/22/2019,Y,360.0
5386,Surfing 101,3620940,46843859,4/22/2019,Y,360.0
5387,Surfing 101,3620940,46845494,4/22/2019,Y,360.0
5388,Surfing 101,3620940,46846606,4/22/2019,Y,360.0
5389,Surfing 101,3620940,46848682,4/22/2019,Y,360.0
5390,Surfing 101,3620940,46849073,4/22/2019,Y,360.0
5391,Surfing 101,3620940,46850621,4/22/2019,Y,360.0
5392,Surfing 101,3620940,46854290,4/22/2019,Y,360.0
5393,Surfing 101,3620940,46855793,4/22/2019,Y,360.0
5394,Surfing 101,3620940,46857724,4/22/2019,Y,360.0
5395,Surfing 101,3620940,46872666,4/22/2019,Y,360.0
5396,Surfing 101,3620940,46876883,4/22/2019,Y,360.0
5397,Surfing 101,3620979,46858126,5/20/2019,Y,360.0
5398,Surfing 101,3620979,46875344,5/20/2019,Y,360.0
5399,Surfing 101,3620979,46878126,5/20/2019,Y,360.0
5400,Surfing 101,3620979,46890828,5/20/2019,Y,360.0

In [14]:
# Amount of classes attended per students
value_counts_HS = surf_101_HS_df["Participant ID"].value_counts()
value_counts_HS

46848962    106
46875282    104
46876799    103
46869531    102
46863178    102
46868996    101
46857181    101
46871123    101
46863022    101
46892864    101
46846095    100
46873595    100
46861904    100
46857186    100
46872115    100
46866343    100
46886737    100
46857740    100
46854847    100
46863147    100
46863077    100
46843252    100
46858992    100
46868024    100
46877014    100
46855204    100
46863487    100
46872724     75
46862430     75
46879337     59
           ...
46871067      1
46891098      1
46878828      1
46878864      1
46879516      1
46875822      1
46875806      1
46857373      1
46859410      1
46869647      1
46865413      1
46871552      1
46883802      1
46863232      1
46863176      1
46846158      1
46859030      1
46866602      1
46875410      1
46879488      1
46879480      1
46852855      1
46852831      1
46858962      1
46875342      1
46858930      1
46885507      1
46856557      1
46877315      1
46870550      1
Name: Participant ID, Length: 344, dtype: int64

In [15]:
# Who attended one class
one_time_HS = value_counts_HS == 1
one_time_HS

46848962    False
46875282    False
46876799    False
46869531    False
46863178    False
46868996    False
46857181    False
46871123    False
46863022    False
46892864    False
46846095    False
46873595    False
46861904    False
46857186    False
46872115    False
46866343    False
46886737    False
46857740    False
46854847    False
46863147    False
46863077    False
46843252    False
46858992    False
46868024    False
46877014    False
46855204    False
46863487    False
46872724    False
46862430    False
46879337    False
            ...
46871067     True
46891098     True
46878828     True
46878864     True
46879516     True
46875822     True
46875806     True
46857373     True
46859410     True
46869647     True
46865413     True
46871552     True
46883802     True
46863232     True
46863176     True
46846158     True
46859030     True
46866602     True
46875410     True
46879488     True
46879480     True
46852855     True
46852831     True
46858962     True
46875342     True
46858930     True
46885507     True
46856557     True
46877315     True
46870550     True
Name: Participant ID, Length: 344, dtype: bool

In [16]:
# Isolate students who only attended one class
one_timers_HS = value_counts_HS[one_time_HS]
one_timers_HS

46862359    1
46858392    1
47027338    1
46862041    1
46889250    1
46851292    1
46889262    1
46884524    1
46868601    1
47728952    1
46851696    1
46871146    1
46865675    1
46875344    1
47400264    1
46866877    1
46872666    1
46874195    1
46843348    1
46868505    1
46856222    1
46875780    1
46862978    1
46862518    1
46850944    1
46885769    1
46890991    1
46856130    1
46848575    1
46885437    1
           ..
46871067    1
46891098    1
46878828    1
46878864    1
46879516    1
46875822    1
46875806    1
46857373    1
46859410    1
46869647    1
46865413    1
46871552    1
46883802    1
46863232    1
46863176    1
46846158    1
46859030    1
46866602    1
46875410    1
46879488    1
46879480    1
46852855    1
46852831    1
46858962    1
46875342    1
46858930    1
46885507    1
46856557    1
46877315    1
46870550    1
Name: Participant ID, Length: 161, dtype: int64

In [17]:
# Df of Students who only attended one class of Surfing 101 HS
one_timers_HS_df = pd.DataFrame(value_counts_HS[one_time_HS], index=None)
one_timers_HS_df.reset_index(inplace=True) 
one_timers_HS_df = one_timers_HS_df.rename(columns={
                    'index':'Participant ID',
                    'Participant ID':'Classes Attended'
})
one_timers_HS_df

     Participant ID  Classes Attended
0          46862359                 1
1          46858392                 1
2          47027338                 1
3          46862041                 1
4          46889250                 1
5          46851292                 1
6          46889262                 1
7          46884524                 1
8          46868601                 1
9          47728952                 1
10         46851696                 1
11         46871146                 1
12         46865675                 1
13         46875344                 1
14         47400264                 1
15         46866877                 1
16         46872666                 1
17         46874195                 1
18         46843348                 1
19         46868505                 1
20         46856222                 1
21         46875780                 1
22         46862978                 1
23         46862518                 1
24         46850944                 1
25         46885769                 1
26         46890991                 1
27         46856130                 1
28         46848575                 1
29         46885437                 1
..              ...               ...
131        46871067                 1
132        46891098                 1
133        46878828                 1
134        46878864                 1
135        46879516                 1
136        46875822                 1
137        46875806                 1
138        46857373                 1
139        46859410                 1
140        46869647                 1
141        46865413                 1
142        46871552                 1
143        46883802                 1
144        46863232                 1
145        46863176                 1
146        46846158                 1
147        46859030                 1
148        46866602                 1
149        46875410                 1
150        46879488                 1
151        46879480                 1
152        46852855                 1
153        46852831                 1
154        46858962                 1
155        46875342                 1
156        46858930                 1
157        46885507                 1
158        46856557                 1
159        46877315                 1
160        46870550                 1

[161 rows x 2 columns]

In [55]:
# Value counts for Surfing 101 MS 
surf_101_MS_df['Participant ID'].value_counts().head()

46897549    33
46904597    18
46901108    18
46895808    18
46907807    18
Name: Participant ID, dtype: int64

In [54]:
# Values Counts for SILT
silt_df['Participant ID'].value_counts().head()

46876991    12
46864770    12
46878556    10
46848962    10
46864094     9
Name: Participant ID, dtype: int64